branches: main

labels:
  hostname: "oscarblue"

pipeline:
  deploy:
    image: alpine:3.16.0
    commands:
      - apk add hugo rsync
      - hugo
      - rsync -rltvz --delete --omit-dir-times ./public/ /oscar.blue/
    volumes:
      - /var/www/oscar.blue:/oscar.blue